### ISSUE TITLE
Angular styles.css not being loaded

### ISSUE THREAD

**Issue by javiersvg** [CompuIves/codesandbox-client#877]
# 🐛 bug report

## How has this issue affected you? What are you trying to accomplish?
The styles of my angular application loaded from github are not being loaded.
As you can see from the console in the sandbox the styles from src/styles.css are not being loaded, even though they are defined in the angular.json file. Sometimes a dependency issue rices but reloading the sandbox makes it work.

The styles file src/styles.css has the following code:
```css
@import "~@angular/material/prebuilt-themes/indigo-pink.css";
body {
  margin: 0px;
  background: #f5f5f5;
}
```
and the material styles nor changing the body background impacts the application.

### Your Environment
| Software         | Name/Version|
| ---------------- | ---------- |
| Сodesandbox  | web
| Browser | chrome
| Operating System | windows 10
